language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: openregister-picker-prototypes
  api_key:
    secure: AEu8iLlfOBg4x+tgchLoYf+uoasOzrm+xIKbPdsuBgI/lDjXa8NckVRVTSJoV4otaat7tSNe/abyO1vEHrP50BEmPbqnhzqNoQU7kSLhF2iu0MkQWyNnoCBU7IbGlWWBeJgN+NfU0VLJefSJabP1SuBKqnZq/23zUgxXtCd/vNW7XiKtlZytInPXmVM6c2920OwQ5sRvfMJI93iofpLFitYNFSs0HJsKyvbcH3IyELuLw35jjdjPAZ6u5l8a4VDInA3/f9qMmCj0xjGkd2A9jjDadMJxf1LmdjY3KaPwJoyKPg4x4HHLcs4ngo1KvY/KQttqpGSlPZWd+YBgI5mUrYptwZbUVzMrsSaSfHk5FEiovlJnIAZG+XrANXBWiTuI6RLBcCFNKWycSF10c2ei8nbdPk5hdS+ESUwvit5TG9eUzbX6H85Av9X6wXiQB3tLUztexlqmbseU4smVti4LVQiV844N2WRwmSg3/B5K3Zk5AkN8/ykB3Tp2oMt6GwACv32zKUNBVeIXE0/wSOJnWrE56OnZkjA+zLYZr182W/IwL+HPA3LifF4N+4GAc4LKtc64ZF/E/WqLNT+rRUs1aKG6r3C8IRuJW3FVQAfEsLJqdZDaQOnLl8VcExzedXXldyeRVe62MkyL+MuduY5oRnWyVuomqiNxUixBUv1TeFg=
